validation: true
yellow_phase_time: 3
episodes: 200
action_interval: 10
gamma: 0.9
epsilon_initial: 1
epsilon_min: 0.0
epsilon_decay: 0.999
use_prioritized: false
batch_size: 32
buffer_size: 10000
learning_start: 2000
#learning_start: 200
update_model_freq: 1
update_target_model_freq: 20
epochs_replay: 1
epochs_initial_replay: 2000
hidden_layers: 2
hidden_nodes: 32
hidden_activation: "relu"
output_activation: "linear"
optimizer: "rmsprop"
loss: "mse"
lr: 0.001
grid_length: 6
#grid_num: 40
grid_num: 25
